// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlsgDRQkl_ZubwMfi5sftWn2r8Uo8ulc',
    appId: '1:1075298230474:android:a2d59738deb2548022d433',
    messagingSenderId: '1075298230474',
    projectId: 'blingbling-app',
    storageBucket: 'blingbling-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC---szyRJBVpxtAnHh2-b1Zoty7S60Ja4',
    appId: '1:1075298230474:ios:4d5ce196717fa56c22d433',
    messagingSenderId: '1075298230474',
    projectId: 'blingbling-app',
    storageBucket: 'blingbling-app.firebasestorage.app',
    androidClientId: '1075298230474-j9kgg12l3d1pdknj37j4e7jl4numuf8o.apps.googleusercontent.com',
    iosClientId: '1075298230474-8qtdn75qbjlle3slodi1kq2ik9st4f7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.blingApp.RunnerTests',
  );
}
